<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
 
 /*
 * hook_menu
 */
 
 function autodownload_menu(){  
     $items['admin/config/user-interface/autodownload'] = array(
       'title' => 'Configure Automatic Downloads', 
       'description' => 'Add automatic links to files from node pages',
       'page callback' => 'autodownload_list_current_pages',
       'page arguments' => array('settings','create','edit','advanced'),
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_NORMAL_ITEM,
     );
     $items['autodownload/settings'] = array(
       'title' => 'Current Auto-downloads',
       'description' => 'Configure automatic downloads per page load.',
       'page callback' => 'autodownload_list_current_pages',
       'weight' => -1,
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_DEFAULT_LOCAL_TASK,
     );
     $items['autodownload/advanced'] = array(
       'title' => 'Advanced Configuration',
       'description' => 'Configure advanced options for Automatic Downloads',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('autodownload_configure_advanced_form'),
       'weight' => 1,
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_LOCAL_TASK, 
     );
     $items['autodownload/create'] = array(
       'title' => 'Create new Auto-Download +',
       'description' => 'Creates a new node auto-download assignment',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('autodownload_create_new_download_form'),
       'weight' => 0,
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_CALLBACK,        
     );
     $items['autodownload/edit'] = array(
       'title' => 'Edit assignment',
       'description' => 'Edits an existing auto-download assignment',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('autodownload_edit_existing_download_form'),
       'weight' => 0,
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_CALLBACK,
     );
     $items['autodownload/delete'] = array(
        'title' => 'Delete assignment',
        'description' => 'Deletes an existing auto-download assignment',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('autodownload_delete_existing_download_form'),
        'weight' => 0,
        'access arguments' => array('administer site configuration'),
        'file' => 'autodownload.admin.inc',
        'type' => MENU_CALLBACK,
      );
     return $items;
 }
?>