<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
 
 /*
 * hook_menu
 */
 
 function autodownload_menu(){  
     $items['admin/config/user-interface/autodownload'] = array(
       'title' => 'Configure Automatic Downloads', 
       'description' => 'Add automatic links to files from node pages',
       'page callback' => 'autodownload_list_current_pages',
       //'page arguments' => array('autodownload_list_current_pages'),
       'access arguments' => array('TRUE'),
       'file' => 'autodownload.admin.inc',
     );
     $items['admin/config/user-interface/autodownload/list'] = array(
       'title' => 'Current Auto-downloads',
       'weight' => -1,
       'type' => MENU_DEFAULT_LOCAL_TASK,
     );
     $items['admin/config/user-interface/autodownload/create'] = array(
       'title' => 'Create+',
       'description' => 'Creates a new node auto-download assignment',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('autodownload_create_new_download_form'),
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_LOCAL_TASK,        
     );
     $items['admin/config/user-interface/autodownload/advanced'] = array(
        'title' => 'Advanced',
        'description' => 'Configure advanced options for Automatic Downloads',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('autodownload_configure_advanced_form'),
        'weight' => 1,
        'access arguments' => array('administer site configuration'),
        'file' => 'autodownload.admin.inc',
        'type' => MENU_LOCAL_TASK, 
      );
     $items['admin/config/user-interface/autodownload/edit/%'] = array(
       'title' => 'Edit Auto-Download',
       'description' => 'Edits an existing auto-download assignment',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('autodownload_edit_node_form',5),
       'access arguments' => array('administer site configuration'),
       'file' => 'autodownload.admin.inc',
       'type' => MENU_VISIBLE_IN_BREADCRUMB,
     );
     $items['admin/config/user-interface/autodownload/delete/%'] = array(
        'title' => 'Delete Auto-Download',
        'description' => 'Deletes an existing auto-download assignment',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('autodownload_delete_node_form',5),
        'access arguments' => array('administer site configuration'),
        'file' => 'autodownload.admin.inc',
        'type' => MENU_VISIBLE_IN_BREADCRUMB,
      );
     return $items;
 }
?>